# Generated by Django 6.0.4 on 2026-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('business_owner', 'Business Owner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
