# Generated by Django 6.0.4 on 2026-04-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_applied_deal_title_order_discount_amount_and_more'),
        ('accounts', '0003_review_is_reported_review_report_reason_and_more'),
    ]

    operations = [
    ]
