# Generated by Django 6.0.4 on 2026-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_customer_name_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
