# Generated by Django 6.0.3 on 2026-04-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='taste_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='preference',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
